# Generated by Django 5.0.7 on 2024-07-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=32)),
                ("city", models.CharField(max_length=111)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("condition", models.CharField(max_length=100)),
                ("temperature", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-date_time"],
            },
        ),
    ]
